language: python
python:
  - "2.7"
  - "3.6"

install:
  - "pip -v install ."

script:
  - "python -V"
  - 'python -c "import dominate; print(dominate.document())"'
  - "python ./test/test.py"
  - "ls -la */*"